version: '3'

services:
  orchestrator:
    container_name: orchestrator
    hostname: orchestrator
    image: ubuntuwithsocat
    networks:
      - poc
    volumes:
      - ../scripts:/docker/scripts
    entrypoint: /docker/scripts/ready-poc-server.sh
    environment:
      - ORCHESTRATOR_HOST=orchestrator
      - ORCHESTRATOR_WAIT_FOR_HOST=midgard

  dash:
    container_name: dash
    hostname: dash
    image: ubuntuwithsocat
    networks:
      - poc
    volumes:
      - ../scripts:/docker/scripts
    entrypoint: /docker/scripts/ready-poc-client.sh
    environment:
      - ORCHESTRATOR_HOST=orchestrator

  bch:
    container_name: bch
    hostname: bch
    image: ubuntuwithsocat
    networks:
      - poc
    volumes:
      - ../scripts:/docker/scripts
    entrypoint: /docker/scripts/ready-poc-client.sh
    environment:
      - ORCHESTRATOR_HOST=orchestrator
      - ORCHESTRATOR_WAIT_FOR_HOST=dash

  thorchain:
    container_name: thorchain
    hostname: thorchain
    image: ubuntuwithsocat
    networks:
      - poc
    volumes:
      - ../scripts:/docker/scripts
    entrypoint: /docker/scripts/ready-poc-client.sh
    environment:
      - ORCHESTRATOR_HOST=orchestrator
      - ORCHESTRATOR_WAIT_FOR_HOST=bch

  midgard:
    container_name: midgard
    hostname: midgard
    image: ubuntuwithsocat
    networks:
      - poc
    volumes:
      - ../scripts:/docker/scripts
    entrypoint: /docker/scripts/ready-poc-client.sh
    environment:
      - ORCHESTRATOR_HOST=orchestrator
      - ORCHESTRATOR_WAIT_FOR_HOST=thorchain

networks:
  poc:
